Name:           perl-Webinject
Version:        1.80
Release:        1%{?dist}
Summary:        Perl Module for testing web services
License:        GPLv2
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Webinject/
Source0:        http://www.cpan.org/modules/by-module/Webinject/Webinject-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 1:5.6.0
BuildRequires:  perl(CPAN)
BuildRequires:  perl(Crypt::SSLeay)
BuildRequires:  perl(Error)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(HTTP::Cookies)
BuildRequires:  perl(HTTP::Request::Common)
BuildRequires:  perl(LWP)
BuildRequires:  perl(Test::Simple)
BuildRequires:  perl(Time::HiRes)
BuildRequires:  perl(XML::Parser)
BuildRequires:  perl(XML::Simple)
Requires:       perl(Crypt::SSLeay)
Requires:       perl(Error)
Requires:       perl(HTTP::Cookies)
Requires:       perl(HTTP::Request::Common)
Requires:       perl(LWP)
Requires:       perl(LWP::Protocol::https)
Requires:       perl(Time::HiRes)
Requires:       perl(XML::Parser)
Requires:       perl(XML::Simple)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
WebInject is a free tool for automated testing of web applications and web
services. It can be used to test individual system components that have
HTTP interfaces (JSP, ASP, CGI, PHP, AJAX, Servlets, HTML Forms, XML/SOAP
Web Services, REST, etc), and can be used as a test harness to create a
suite of [HTTP level] automated functional, acceptance, and regression
tests. A test harness allows you to run many test cases and collect/report
your results. WebInject offers real-time results display and may also be
used for monitoring system response times.

%prep
%setup -q -n Webinject-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes LICENSE MYMETA.json MYMETA.yml
%{perl_vendorlib}/*
%{_bindir}/*
%{_mandir}/man3/*

%changelog
* Wed Oct 30 2013 Sebastian Trebitz <sebastian@trebitz.eu> 1.80-1
- Specfile autogenerated by cpanspec 1.78.
